// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7phuVOxmzkPcbL5JCP4SgbXEebzh2YVQ',
    appId: '1:1013946503450:web:0da81b5de5214a63c25ca3',
    messagingSenderId: '1013946503450',
    projectId: 'ecommerce-app-ceaf0',
    authDomain: 'ecommerce-app-ceaf0.firebaseapp.com',
    storageBucket: 'ecommerce-app-ceaf0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2CbKfrkIR1OPK1O9I7mfZHeGRFX9JsB4',
    appId: '1:1013946503450:android:05a5b2f8a0faf85cc25ca3',
    messagingSenderId: '1013946503450',
    projectId: 'ecommerce-app-ceaf0',
    storageBucket: 'ecommerce-app-ceaf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1RGbLzhT0iLkOE9hCOWXpoLNIlU6lXOQ',
    appId: '1:1013946503450:ios:00601e2dbf6c815bc25ca3',
    messagingSenderId: '1013946503450',
    projectId: 'ecommerce-app-ceaf0',
    storageBucket: 'ecommerce-app-ceaf0.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1RGbLzhT0iLkOE9hCOWXpoLNIlU6lXOQ',
    appId: '1:1013946503450:ios:00601e2dbf6c815bc25ca3',
    messagingSenderId: '1013946503450',
    projectId: 'ecommerce-app-ceaf0',
    storageBucket: 'ecommerce-app-ceaf0.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7phuVOxmzkPcbL5JCP4SgbXEebzh2YVQ',
    appId: '1:1013946503450:web:81ba57b4202a4d5ac25ca3',
    messagingSenderId: '1013946503450',
    projectId: 'ecommerce-app-ceaf0',
    authDomain: 'ecommerce-app-ceaf0.firebaseapp.com',
    storageBucket: 'ecommerce-app-ceaf0.appspot.com',
  );
}
